--CREATE DATABASE videos;
--use videos;
--CREATE TABLE video(
--    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 --   direccion VARCHAR(100) NOT NULL,
--    category VARCHAR(15),
--    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);
--show tables;
--describe video;
